### ISSUE TITLE
Missing Cities in the created dictionary

### ISSUE THREAD

**Issue by pe-mn** [agalea91/city_to_state_dictionary#1]
missing = {
  'Virginia Beach': 'Virginia',
  'Stamford': 'Connecticut', 
  'Lexington Fayette': 'Kentucky',
  'Waterbury': 'Connecticut',
  'New York': 'New York',
  'Newport News': 'Virginia',
  'Hampton': 'Virginia',
  'Chesapeake': 'Virginia',
  'Hartford': 'Connecticut',
  'Saint Louis': 'Missouri',
  'Winston Salem': 'North Carolina',
  'New Haven': 'Connecticut',
  'San Antonio': 'Texas',
  'Wichita Falls': 'Texas',
  'Richardson': 'Texas',
  'Waco': 'Texas',
  'Plano': 'Texas',
  'Killeen': 'Texas',
  'Laredo': 'Texas',
  'Vallejo': 'California',
  'Visalia': 'California',
}

city_to_state = {**city_to_state, **missing}

**Comment by zazencodes** [comment]
Feel free to submit a PR

**Comment by zazencodes** [comment]
#2
